version: "3.8"

services:
  auth:
    build: ./auth
    ports:
      - "5000:5000"
    environment:
      - PORT=5000

  backend1:
    build: ./backend
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - AUTH_URL=http://auth:5000

  backend2:
    build: ./backend
    ports:
      - "4002:4002"
    environment:
      - PORT=4002
      - AUTH_URL=http://auth:5000

  frontend1:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - BACKEND_URL=http://backend1:4000
      - AUTH_URL=http://auth:5000

  frontend2:
    build: ./frontend
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - BACKEND_URL=http://backend2:4002
      - AUTH_URL=http://auth:5000

networks:
  default:
    driver: bridge
