services:
  auth:
    build: ./auth
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      PORT: ${AUTH_PORT:-5000}
      MONGO_URI: ${MONGO_ATLAS_URI}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - ${AUTH_PORT:-5000}:5000

  backend1:
    build: ./backend
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      PORT: ${BACKEND1_PORT:-4000}
      MONGO_URI: ${MONGO_ATLAS_URI}
      JWT_SECRET: ${JWT_SECRET}
      REDIS_URL: ${REDIS_URL}
      INSTANCE_NAME: backend1
    ports:
      - ${BACKEND1_PORT:-4000}:4000
    depends_on:
      - auth

  backend2:
    build: ./backend
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      PORT: ${BACKEND2_PORT:-4001}
      MONGO_URI: ${MONGO_ATLAS_URI}
      JWT_SECRET: ${JWT_SECRET}
      REDIS_URL: ${REDIS_URL}
      INSTANCE_NAME: backend2
    ports:
      - ${BACKEND2_PORT:-4001}:4001
    depends_on:
      - auth

  frontend1:
    build:
      context: ./frontend
      args:
        # Public (browser) URLs must use a host resolvable outside the Docker network
        NEXT_PUBLIC_API_URL: ${FRONTEND1_PUBLIC_BACKEND_URL:-http://localhost:${BACKEND1_PORT:-4000}}
        NEXT_PUBLIC_SOCKET_URL: ${FRONTEND1_PUBLIC_BACKEND_URL:-http://localhost:${BACKEND1_PORT:-4000}}
        NEXT_PUBLIC_AUTH_URL: ${AUTH_PUBLIC_URL:-http://localhost:${AUTH_PORT:-5000}}
    environment:
      PORT: ${FRONTEND1_PORT:-3000}
      NEXT_PUBLIC_API_URL: ${FRONTEND1_PUBLIC_BACKEND_URL:-http://localhost:${BACKEND1_PORT:-4000}}
      NEXT_PUBLIC_SOCKET_URL: ${FRONTEND1_PUBLIC_BACKEND_URL:-http://localhost:${BACKEND1_PORT:-4000}}
      NEXT_PUBLIC_AUTH_URL: ${AUTH_PUBLIC_URL:-http://localhost:${AUTH_PORT:-5000}}
    ports:
      - ${FRONTEND1_PORT:-3000}:3000
    depends_on:
      - backend1
      - auth

  frontend2:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_URL: ${FRONTEND2_PUBLIC_BACKEND_URL:-http://localhost:${BACKEND2_PORT:-4001}}
        NEXT_PUBLIC_SOCKET_URL: ${FRONTEND2_PUBLIC_BACKEND_URL:-http://localhost:${BACKEND2_PORT:-4001}}
        NEXT_PUBLIC_AUTH_URL: ${AUTH_PUBLIC_URL:-http://localhost:${AUTH_PORT:-5000}}
    environment:
      PORT: ${FRONTEND2_PORT:-3001}
      NEXT_PUBLIC_API_URL: ${FRONTEND2_PUBLIC_BACKEND_URL:-http://localhost:${BACKEND2_PORT:-4001}}
      NEXT_PUBLIC_SOCKET_URL: ${FRONTEND2_PUBLIC_BACKEND_URL:-http://localhost:${BACKEND2_PORT:-4001}}
      NEXT_PUBLIC_AUTH_URL: ${AUTH_PUBLIC_URL:-http://localhost:${AUTH_PORT:-5000}}
    ports:
      - ${FRONTEND2_PORT:-3001}:3001
    depends_on:
      - backend2
      - auth

  # Uncomment to run local Redis instead of external Aiven
  # redis:
  #   image: valkey/valkey:7-alpine
  #   container_name: chatapp_redis
  #   ports:
  #     - ${REDIS_PORT:-6379}:6379
  #   command: ["valkey-server", "--save", "", "--appendonly", "no"]
  #   healthcheck:
  #     test: ["CMD", "valkey-cli", "ping"]
  #     interval: 5s
  #     timeout: 3s
  #     retries: 20

volumes:
  mongo_data: {}

networks:
  default:
    driver: bridge
